#!/usr/bin/env python3
"""
Trending GitHub Repositories Reporter

Fetches the top 10 trending repositories for a given programming language
from the GitHub Trending page and generates a Markdown report.

Only standard library modules are used.
"""

import argparse
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
import re
import html

# ----------------------------------------------------------------------
# Configuration and environment validation
# ----------------------------------------------------------------------
DEFAULT_BASE_URL = "https://github.com/trending"

def get_base_url():
    """
    Return the base URL for GitHub Trending. Allows override via the
    GITHUB_TRENDING_BASE_URL environment variable.
    """
    env_var = "GITHUB_TRENDING_BASE_URL"
    base_url = os.getenv(env_var, DEFAULT_BASE_URL).strip()
    if not base_url:
        print(f"Error: Environment variable {env_var} is set but empty.", file=sys.stderr)
        sys.exit(1)
    return base_url

# ----------------------------------------------------------------------
# Networking utilities with robust error handling
# ----------------------------------------------------------------------
def fetch_url(url):
    """
    Retrieve the content at `url` using urllib with a custom User-Agent.
    Returns the page content decoded as UTF-8.
    """
    headers = {
        "User-Agent": "Mozilla/5.0 (compatible; TrendingFetcher/1.0)",
        "Accept-Encoding": "identity",
    }
    req = urllib.request.Request(url, headers=headers)

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            # GitHub will return UTF-8; explicit decode for safety
            charset = resp.headers.get_content_charset() or "utf-8"
            return resp.read().decode(charset, errors="replace")
    except urllib.error.HTTPError as e:
        print(f"HTTP error {e.code} while accessing {url}: {e.reason}", file=sys.stderr)
        sys.exit(1)
    except urllib.error.URLError as e:
        print(f"Network error while accessing {url}: {e.reason}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error while fetching {url}: {e}", file=sys.stderr)
        sys.exit(1)

# ----------------------------------------------------------------------
# HTML parsing (simple, using regex & html.unescape)
# ----------------------------------------------------------------------
ARTICLE_RE = re.compile(r'<article[^>]*class="[^"]*Box-row[^"]*"[^>]*>(.*?)</article>', re.S)
HREF_RE = re.compile(r'href="/([^/]+/[^/]+)"')
DESC_RE = re.compile(r'<p class="[^"]*color-fg-muted[^"]*">(.*?)</p>', re.S)
STARS_RE_TEMPLATE = r'href="/{repo_path}/stargazers"[^>]*>([\d,]+)</a>'

def clean_html(text):
    """Remove HTML tags and unescape HTML entities."""
    text = re.sub(r'<[^>]+>', '', text)      # strip tags
    return html.unescape(text).strip()

def parse_trending_page(html_content):
    """
    Extract repository information from the GitHub Trending page HTML.
    Returns a list of dictionaries with keys: full_name, url, description, stars.
    """
    repos = []
    for article_match in ARTICLE_RE.finditer(html_content):
        article_html = article_match.group(1)

        # Repository path (owner/repo)
        href_match = HREF_RE.search(article_html)
        if not href_match:
            continue
        repo_path = href_match.group(1).strip()
        full_name = repo_path  # e.g., "owner/repo"
        repo_url = f"https://github.com/{repo_path}"

        # Description (optional)
        desc_match = DESC_RE.search(article_html)
        description = clean_html(desc_match.group(1)) if desc_match else ""

        # Stars
        stars_pattern = re.compile(STARS_RE_TEMPLATE.format(repo_path=repo_path), re.S)
        stars_match = stars_pattern.search(article_html)
        stars = stars_match.group(1).replace(",", "") if stars_match else "0"

        repos.append({
            "full_name": full_name,
            "url": repo_url,
            "description": description,
            "stars": stars,
        })
    return repos

# ----------------------------------------------------------------------
# Markdown generation
# ----------------------------------------------------------------------
def generate_markdown(language, repos):
    """
    Produce a markdown string summarising the top repositories.
    """
    md_lines = [
        f"# Trending GitHub repositories for `{language}`",
        "",
        "Generated by the **Trending GitHub Reporter** script.",
        "",
    ]

    for idx, repo in enumerate(repos[:10], start=1):
        md_lines.append(f"## {idx}. [{repo['full_name']}]({repo['url']})")
        md_lines.append("")
        if repo["description"]:
            md_lines.append(f"*{repo['description']}*")
            md_lines.append("")
        md_lines.append(f"**Stars:** {repo['stars']}")
        md_lines.append("")

    return "\n".join(md_lines)

# ----------------------------------------------------------------------
# Main execution flow
# ----------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Fetch top 10 trending GitHub repositories for a given language and output a markdown report."
    )
    parser.add_argument(
        "language",
        nargs="?",
        default="python",
        help="Programming language to filter trending repositories (default: python).",
    )
    parser.add_argument(
        "-o", "--output",
        help="Path to write the markdown report. Defaults to 'trending_<language>.md'.",
    )
    args = parser.parse_args()

    language = args.language.strip()
    if not language:
        print("Error: Language argument cannot be empty.", file=sys.stderr)
        sys.exit(1)

    base_url = get_base_url()
    query = urllib.parse.urlencode({"l": language})
    trending_url = f"{base_url}?{query}"

    print(f"Fetching trending repositories for language: {language}")
    page_html = fetch_url(trending_url)

    repos = parse_trending_page(page_html)
    if not repos:
        print("No repositories found or page parsing failed.", file=sys.stderr)
        sys.exit(1)

    markdown = generate_markdown(language, repos)

    output_path = args.output or f"trending_{language.lower()}.md"
    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(markdown)
        print(f"Markdown report written to: {output_path}")
    except OSError as e:
        print(f"Failed to write report to {output_path}: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()